name: KindeCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install tools and generate code
      run: make install-tools

    - name: Generate, build and test
      run: make all

    - id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
         go-package: ./...
